import { Injectable } from '@angular/core'
import { Product } from '../models/Product'
import { Observable } from 'rxjs'

@Injectable({
    providedIn: 'root',
})
export class CartService {
    cart: Product[] = []

    constructor() {}

    //  the following methods are used to add, remove, and clear items from the cart
    // they were ALL generated by github copilot and are only here for reference
    addToCart(product: Product) {
        this.cart.push(product)
        console.log(`Cart: `, this.cart)
    }

    getCart(): Product[] {
        return this.cart
    }

    removeFromCart(product: Product) {
        const index = this.cart.indexOf(product)
        if (index > -1) {
            this.cart.splice(index, 1)
        }
    }

    clearCart() {
        this.cart = []
    }

    getCartTotal(): number {
        let total = 0
        this.cart.forEach((product) => {
            total += product.price
        })
        return total
    }

    getCartCount(): number {
        return this.cart.length
    }

    getCartItems(): Product[] {
        return this.cart
    }
    // this is where the auto - generated code ends
}
